- README.md
closes #9 
- Broken link is replaced by working link
> Broken link replaced

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- LICENSE
- README.md
- Added CODE_OF_CONDUCT.md
- Added CONTRIBUTING.md
- Added LICENSE (MIT)
> Add recommended community standards

- src/App.js
- src/Components/Footer/Footer.css
- src/Components/Footer/Footer.jsx
- src/Components/Navbar/Navbar.jsx
- src/Components/index.js
> Added Footer Component in reference to issue #15

- CONTRIBUTING.md
Fixed the broken syntax for steps to follow to contribute
> Fixed syntax in CONTRIBUTING.md

- openlysource-backend/controllers/Opportunities/opportunities.js
- openlysource-backend/package-lock.json
- openlysource-backend/routes/Opportunities/index.js
- openlysource-backend/services/Opportunities/index.js
Update Event api : 
- method: put
- route: /api/opportunities/event/:event_id
Delete Event api 
- method: delete 
- route: /api/opportunities/event/:event_id
> updateEvent and deleteEvent apis 

- src/App.css
- src/Components/Navbar/Navbar.css
- src/Components/Opportunities/Opportunities.css
- src/index.css
Updated font family  with sofia sans
> Update font family

- README.md
> added some badges in readme

- package-lock.json
- package.json
following Readme for starting project locally but, axios package is not there in package.json, So here I made the fix by just an
`npm i axios`
> added axios in package.json

- openlysource-backend/controllers/Members/members.js
- openlysource-backend/index.js
- openlysource-backend/models/index.js
- openlysource-backend/models/member.js
- openlysource-backend/routes/Members/index.js
- openlysource-backend/services/member/index.js
member route: 
- get all members = api/members (get)
- add member -api/members (post)
- delete member -api/members/:id (delete)
- update member -api/members/:id (put)
> member route added

- package-lock.json
- src/Components/About-us/AboutElements.css
- src/Components/Members/Member.js
- src/Components/Navbar/Navbar.css
- src/Components/Navbar/Navbar.jsx
Made Navbar Responsive. It requires additional functionality for screenwidths below 1000px
> making navbar responsive, issue #49

- package-lock.json
- package.json
installed `reactstrap`
* add reactstrap in `package.json`
*  update `package-lock` file accordingly
> added reactstrap in package.json

- openlysource-backend/controllers/Members/members.js
- openlysource-backend/models/member.js
- src/Components/Members/Member.js
Issues Resolved : #43 #53 
* fire post request with form data to `/api/members` route
* making profile picture not required(temporarily)
* Now from data is saving into the DB successfully.
* As soon as form is submitted a new card should pop-up below
> connected members frontend to the backend 

- src/Components/Members/Member.js
- src/Components/Members/MemberCard.js
* rendering cards on initial page load
* rendering card on each form submit
* separate card as a new component
> Auto card popup on form submission

- src/Components/Navbar/Navbar.css
- src/Components/Navbar/Navbar.jsx
* Wrapped logo inside Link
* Change the CSS accordingly
> make logo clickable(refrencing to home page)

- src/Components/About-us/About.js
- src/Components/About-us/AboutElements.css
fixes #65 
Notes:
Ran prettier through the js file. Changes I made where `<Card style={{ width: "15rem" }}>` at line 76 and 87.
Preview image:
> fix css in Join us page

- package-lock.json
- public/index.html
- src/Components/Header/Header.css
- src/Components/Navbar/Navbar.css
I have made the landing page responsive. please review @hparashar27
> landing page responsiveness done

- package-lock.json
- src/App.js
- src/Components/About-us/About.js
- src/Components/Resources/Resources.css
- src/Components/Resources/Resources.js
Hey.. I have included the necessary resources for the beginners to get started with the open source!
You can view resource page by clicking "Get Started" button in the about-us page!
This fixes #41
> Resources page Completed

- openlysource-backend/package-lock.json
- src/Components/Header/Header.css
- src/Components/Header/Header.jsx
fixes issue - 
- #73 
**Before** - 
**After**
Please review it and tell me your feedback.
> changed join us button div

- src/Components/About-us/AboutElements.css
- src/Components/Resources/Resources.css
- src/Components/Resources/Resources.js
I have Fixed the responsiveness of resources page, it now looks and works well even on smaller screens.
> Fix: Responsive Design To Resources Page

- src/Components/About-us/About.js
- src/Components/About-us/AboutElements.css
This is the new about us page being responsive.
Closes issue-
- #57 
https://user-images.githubusercontent.com/75900118/226117304-81632ace-0955-424c-b02e-ac195fd9598d.mp4
> Made about us page responsive
